name: Publish dist
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Build package
        run: |
          ./scripts/install-osx-dependencies.sh
          yarn install
          yarn build
          yarn dist macos-amd64
          ls dist
