name: Publish dist
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Build package
        run: |
          ./scripts/install-osx-dependencies.sh
          yarn install
          yarn build
          yarn dist macos-amd64
          ls dist

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/garden-0.12.56-macos-amd64.tar.gz"
          body: |
            Release 0.12.56 with pulumi rm stack fix.

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          tag: 0.12.56
          commit: ${{ github.sha }}
